### ISSUE TITLE
NameError (uninitialized constant Net::HTTPS)

### ISSUE THREAD

**Issue by drewterry** [mileszim/webpurify-gem#11]
When setting `enterprise` option `true`, requests return this error.

It appears that [this line](https://github.com/mileszim/webpurify-gem/blob/5a52ae9d58af9e4abca4627f93fcb91eda09b333/lib/web_purify/request.rb#L69) uses `Net::HTTPS` instead of using `Net::HTTP` and setting `http.use_ssl = true`.

Using Ruby 2.5.1 and Rails 5.2.1.

**Comment by mileszim** [comment]
Nice catch! Thanks

**Comment by mileszim** [comment]
It's live https://rubygems.org/gems/webpurify/versions/1.0.1
